[FEATURE] first prototype of Annotation1DVerticalLineItem
OpenMS/OpenMS pull request #5005
Opened 2020-10-08 11:17 UTC by JeeH-K

# Description

A simple prototype of annotation item, Annotation1DVerticalLineItem

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

2020-10-08 15:22 UTC, cbielow commented on src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
> +#include <vector>
not needed

2020-10-08 15:23 UTC, cbielow commented on src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
> +#include <OpenMS/DATASTRUCTURES/DPosition.h>
not needed

2020-10-08 15:24 UTC, cbielow commented on src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
> +  Annotation1DVerticalLineItem::Annotation1DVerticalLineItem(const Annotation1DVerticalLineItem & rhs) :
use ` = default;` instead?

2020-10-08 15:25 UTC, cbielow commented on src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
> +  Annotation1DVerticalLineItem::~Annotation1DVerticalLineItem()
also defaultable

2020-10-08 15:27 UTC, cbielow commented on src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
> +    if (canvas->isMzToXAxis())
code in if/else cases is identical.
This is probably a bug

2020-10-08 15:28 UTC, cbielow commented on src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
> +    Annotation1DVerticalLineItem(const double& x, const QColor& color, const QString & tex="");
typo: `text`

2020-10-08 15:28 UTC, cbielow commented on src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
> +    Annotation1DVerticalLineItem(const double& x, const QColor& color, const QString & tex="");
can you add docs what the text does and where it shows up

2020-10-08 15:30 UTC, cbielow commented on src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
> +  void Annotation1DVerticalLineItem::draw(Spectrum1DCanvas * const canvas, QPainter & painter, bool flipped)
coding convention: put `&`, `*` etc next to the type, e.g. `QPainter&`.
Applies to a lot of places here. Should be automatically fixable with clang-format if you happen to have that available.

2020-10-08 15:30 UTC, cbielow requested changes
nice. See comments.
Can you provide a screenshot of how it looks like?

2020-10-08 15:43 UTC, timosachsenberg commented
![image](https://user-images.githubusercontent.com/5803621/95440364-286e7900-0959-11eb-82da-6c2339e743c8.png)

2020-10-09 06:29 UTC, timosachsenberg commented
/rebase

2020-10-09 08:35 UTC, merged