take first native id format as represenative
OpenMS/OpenMS pull request #5130
Opened 2021-01-15 20:10 UTC by timosachsenberg

# Description

Using FileHandler to load mzMLs with the flag for automatic filename reannotation
removed the native id format CV term. It is now preserved.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.

2021-01-15 23:15 UTC, jpfeuffer requested changes
Rest looks good.

2021-01-15 23:15 UTC, jpfeuffer commented on src/openms/source/FORMAT/MascotGenericFile.cpp
> +      OPENMS_LOG_WARN << "MascatGenericFile: no native ID accession." << endl;
```suggestion
      OPENMS_LOG_WARN << "MascotGenericFile: no native ID accession." << endl;
```

2021-01-15 23:15 UTC, jpfeuffer commented on src/openms/source/FORMAT/FileHandler.cpp
> +                          << " will take only first one as for rewriting." << endl;
```suggestion
                          << " will take only first one for rewriting." << endl;
```

2021-01-15 23:15 UTC, jpfeuffer commented on src/openms/source/FORMAT/MascotGenericFile.cpp
> +        OPENMS_LOG_WARN << "MascatGenericFile: empty native ID accession." << endl;
```suggestion
        OPENMS_LOG_WARN << "MascotGenericFile: empty native ID accession." << endl;
```

2021-01-16 14:00 UTC, merged

2021-01-16 14:00 UTC, timosachsenberg commented
Merging now because I want to create new docker container