added mzQC export for the QCCalculator
OpenMS/OpenMS pull request #5191
Opened 2021-02-25 08:27 UTC by axelwalter

# Description

Added a function for QCFile to export as mzQC in JSON format. 

# TODO:
- calculate SHA
- add option to store as qcML or mzQC

2021-02-25 09:07 UTC, timosachsenberg requested changes
Nice thanks for the contribution

2021-02-25 09:07 UTC, timosachsenberg commented on src/openms/source/FORMAT/QcMLFile.cpp
> +        << String(18, ' ') << "\"value\": \"" << "\"\n" // how to calculate SHA sum?
from MSExperiment you can get the SourceFile https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/SourceFile_test.cpp#L150

2021-02-25 09:30 UTC, cbielow commented
interesting PR.
Can you motivate a bit why mzQC is added into the old qcML architecture?

The way I see it (and I think @mwalzer agrees): qcML is dead, so my first take would have been to start mzQC from scratch instead of trying to adapt old code. But that's just me.

We also have https://github.com/nlohmann/json already integrated into OpenMS, to immediate use.
To write a JSON string, you can just do (taken from the example section of `json`):

```
json j2 = {
  {"pi", 3.141},
  {"happy", true},
  {"name", "Niels"},
  {"nothing", nullptr},
  {"answer", {
    {"everything", 42}
  }},
  {"list", {1, 0, 2}},
  {"object", {
    {"currency", "USD"},
    {"value", 42.99}
  }}
};
```
This would avoid the need for manually stitching everything together and gives the correct indentations automatically etc...

The final remark: the official file ending of mzQC will be `.mzQC` (I think this is not part of the spec document yet, but we agreed upon that in the last mzQC meeting, if I remember correctly).

2021-02-25 09:30 UTC, cbielow commented
I'm happy to discuss more in a TC. maybe in the afternoon?

2021-02-25 09:57 UTC, axelwalter commented
Thanks for the feedback, we can discuss it in the afternoon meeting.

2021-02-26 09:58 UTC, axelwalter commented
Closing this pull request, revert changes and create new MzQCFile and MzQCCalculator independently of the old qcML stuff.

2021-02-26 09:58 UTC, closed without merging