Added wrap-doc methods
OpenMS/OpenMS pull request #5407
Opened 2021-07-11 17:48 UTC by rahul799

# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2021-07-13 08:25 UTC, oliveralka approved these changes
looks good! 

Have to check the failing tests.

2021-07-13 08:29 UTC, oliveralka requested changes

2021-07-13 08:29 UTC, oliveralka commented on src/pyOpenMS/pxds/FASTAFile.pxd
> +        bool atEnd() nogil except + Boolean function to check if streams is at end of file
Missing "# wrap-doc"

2021-07-13 12:05 UTC, rahul799 commented on src/pyOpenMS/pxds/FASTAFile.pxd
> +        bool atEnd() nogil except + Boolean function to check if streams is at end of file
This is fixed now.

2021-07-14 06:19 UTC, oliveralka approved these changes

2021-07-14 06:19 UTC, merged