Swath
OpenMS/OpenMS pull request #5635
Opened 2021-11-04 08:25 UTC by vmusch

# Description

- OpenMS Matrix data structure added to OpenSwath
- MRMScoring of Openswath revised
- MRMScoring test extended

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ x] Make sure that you are listed in the AUTHORS file
- [ x] Add relevant changes and new features to the CHANGELOG file
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] New and existing unit tests pass locally with my changes
- [ x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2021-11-04 18:59 UTC, hroest commented
is Matrix.h just duplicated from OpenMS?

2021-11-04 20:22 UTC, cbielow commented
Yes, though without the openms dependencies.

2021-11-05 12:44 UTC, vmusch commented
rebuild jenkins

2021-11-10 13:12 UTC, cbielow commented on src/pyOpenMS/pxds/MRMScoring.pxd
> +    cdef cppclass MRMScoring "OpenMS::MRMScoring":
should be `cdef cppclass MRMScoring MRMScoring:`  ???

2021-11-10 15:42 UTC, cbielow commented
tests pass.
Ready for merge.

Duplication of Matrix class was undone. Makes it a lot cleaner.

2021-11-10 19:54 UTC, cbielow commented
rebuild jenkins

2021-11-11 10:01 UTC, timosachsenberg requested changes
Thanks! only minor comments.
Maybe extend the PR description a bit more why the changes have been made and which changes have been made.
This helps immensely if we need to go back to check why some changes have been made.

2021-11-11 11:04 UTC, vmusch commented on src/tests/class_tests/openswathalgo/MRMScoring_test.cpp
> +  std::vector<double> ms1intensity2 {10.0, 115.0, 180.0, 280.0, 330.0, 340.0, 390.0, 320.0, 300.0, 250.0, 100.0};
https://github.com/OpenMS/OpenMS/blob/7dc444e43a81508e19b5c4c8d9eb726aec1f9ae5/src/tests/class_tests/openswathalgo/MRMScoring_test.cpp#L135
I had made a mistake when copying the line (forgot a one)

2021-11-11 12:35 UTC, merged

2021-11-12 14:38 UTC, hroest commented
> Duplication of Matrix class was undone. Makes it a lot cleaner.

however now part of the algorithm part got moved out of OpenSwathAlgo, raising the question how much purpose this really still serves

2021-11-12 14:42 UTC, timosachsenberg commented
> Maybe extend the PR description a bit more why the changes have been made and which changes have been made.
> This helps immensely if we need to go back to check why some changes have been made.

maybe @vmusch or @cbielow can add a few lines why this has been done

2021-11-22 09:07 UTC, timosachsenberg commented
@vmusch @cbielow could your changes here be related to 
https://github.com/OpenMS/OpenMS/issues/5668

2021-11-22 13:31 UTC, cbielow commented
not sure. The easiest test would be to try some older commit and see if the problem persists.
Even OpenMS 2.7 should do?!