compile fixes
OpenMS/OpenMS pull request #5764
Opened 2022-01-26 12:22 UTC by timosachsenberg

# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- /rebase will try to rebase the PR on the current develop branch.
- /reformat (experimental) applies the clang-format style changes as additional commit
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)

2022-01-26 14:41 UTC, jpfeuffer requested changes
I would just comment out unused vars

2022-01-26 14:41 UTC, jpfeuffer commented on src/openms_gui/source/VISUAL/SpectraTreeTab.cpp
> +  void SpectraTreeTab::itemSelectionChange_(QTreeWidgetItem* current, QTreeWidgetItem*)
```suggestion
  void SpectraTreeTab::itemSelectionChange_(QTreeWidgetItem* current, QTreeWidgetItem* /*previous*/)
```

2022-01-26 14:41 UTC, jpfeuffer commented on src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
> +  void SpectraIDViewTab::updatedSingleProteinCell_(QTableWidgetItem*)
```suggestion
  void SpectraIDViewTab::updatedSingleProteinCell_(QTableWidgetItem* /*item*/)
```

2022-01-26 15:31 UTC, merged

2022-01-27 00:45 UTC, jpfeuffer commented
This broke the TOPPView_test

2022-01-27 07:35 UTC, timosachsenberg commented
why? are you sure that this is related to https://github.com/OpenMS/OpenMS/pull/5764/files