Combine residues into one modification
OpenMS/OpenMS pull request #6376
Opened 2022-10-09 17:25 UTC by Amit0617

## Description

fixes #6203 

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2022-10-23 11:43 UTC, poshul requested changes

2022-10-23 11:43 UTC, poshul commented on src/openms/include/OpenMS/CHEMISTRY/VarMod.h
> +// $Maintainer: Chris Bielow $
@Amit0617 can you correct the authors and maintainers?

2022-10-23 11:43 UTC, poshul commented on src/openms/source/CHEMISTRY/VarMod.cpp
> +// $Maintainer: Timo Sachsenberg $
Same with this as the .h file

2022-10-23 12:19 UTC, jpfeuffer commented
I think this needs some help if this should go into 3.0

2022-10-30 03:26 UTC, Amit0617 commented
I am getting really tight on time. If someone willing to take it forward, please go ahead.

2023-01-25 07:36 UTC, Amit0617 commented
Hello there, bumping it

2023-01-25 14:52 UTC, jpfeuffer commented
your submodules are messed up. please open a new clean PR.

2023-01-25 14:52 UTC, closed without merging