Fixes for new TOPPView
OpenMS/OpenMS pull request #6519
Opened 2022-12-01 10:25 UTC by cbielow

## Description

Fixes some issues mentioned in https://github.com/OpenMS/OpenMS/issues/6423

Notably:
 + fix plotting of precursor positions in 2D View
 + show intensity when mouse-hovering over a data point
![image](https://user-images.githubusercontent.com/6008722/205028771-941d3cd2-5187-4ab1-99c8-21822f8fa1b6.png)

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2022-12-01 11:55 UTC, timosachsenberg approved these changes

2022-12-01 12:50 UTC, poshul commented
rebuild jenkins

2022-12-01 14:12 UTC, jpfeuffer commented
ALL of them actually show this

2022-12-01 14:13 UTC, jpfeuffer requested changes
see comment above

2022-12-01 14:55 UTC, jpfeuffer commented
When it zooms it switches axes or some weird stuff

2022-12-01 15:46 UTC, timosachsenberg commented
MS2 look better for me now but I also observe the switching when zooming or panning:
![image](https://user-images.githubusercontent.com/5803621/205096760-b6c0bb66-757a-4f39-898d-8914799ea8e2.png)
just panned a bit and looks good again:
![image](https://user-images.githubusercontent.com/5803621/205096920-076b642a-4783-4ad4-85b3-7b3dfc5d5a1a.png)

2022-12-01 17:00 UTC, jpfeuffer commented
With MS2 I meant the 1D view.
Nothing is shown there anymore

2022-12-02 07:08 UTC, timosachsenberg commented
works for me (there was just a scaling to 1.0 issue that went away after pressing one of the scale buttons)
![image](https://user-images.githubusercontent.com/5803621/205235527-598d66c4-6163-4d6e-89d0-9818f508341e.png)

2022-12-02 07:11 UTC, timosachsenberg commented
zooming in by mouse wheel seems to work but selecting a region will not automatically scale:
![image](https://user-images.githubusercontent.com/5803621/205236168-8e7e92dd-aa70-4cfa-ae6e-3e06f34ed453.png)
only if % button is pressed

2022-12-02 09:10 UTC, timosachsenberg commented
```
diff --git a/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp b/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
@@ -1915,6 +1919,8 @@ namespace OpenMS
     }
     selection_view_->setCurrentIndex(DataSelectionTabs::IDENT_IDX); //switch to ID view
     selection_view_->currentTabChanged(DataSelectionTabs::IDENT_IDX);
+    setIntensityMode(PlotCanvas::IM_SNAP);
+    updateMenu();
   }
```
in annotateWithIdentifications seem to fix the first issue of initial scaling to 1.0

2022-12-02 11:00 UTC, timosachsenberg commented
regarding the peak annotations I found this version that has the improved logic: 

https://github.com/OpenMS/OpenMS/blob/973674372b1e97e542acdb6d59295f492b3c051c/src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DPeakItem.cpp

2022-12-02 13:06 UTC, timosachsenberg commented on src/openms_gui/source/VISUAL/Plot2DCanvas.cpp
> +    if (unit_mapper_.getDim(DIM::X).getUnit() != DIM_UNIT::INT && unit_mapper_.getDim(DIM::X).getUnit() != DIM_UNIT::INT)
```suggestion
    if (unit_mapper_.getDim(DIM::X).getUnit() != DIM_UNIT::INT && unit_mapper_.getDim(DIM::Y).getUnit() != DIM_UNIT::INT)
```

2022-12-05 16:00 UTC, cbielow commented
> MS2 look better for me now but I also observe the switching when zooming or panning: ![image](https://user-images.githubusercontent.com/5803621/205096760-b6c0bb66-757a-4f39-898d-8914799ea8e2.png) just panned a bit and looks good again: ![image](https://user-images.githubusercontent.com/5803621/205096920-076b642a-4783-4ad4-85b3-7b3dfc5d5a1a.png)

this was caused by trying to auto-guess the MS level when creating an AreaIterator. Bad idea.
Its fixed now.

2022-12-05 16:03 UTC, cbielow commented
Pressing `Save IDs` is now also fixed, with some very interesting background story...
https://github.com/OpenMS/OpenMS/pull/6519/commits/83580fb35e65a12d062a3b40c031da84fe4d04a2

2022-12-06 08:09 UTC, timosachsenberg commented
nice. another thing:
I think there might be something wrong with mapping the intensity type to the button index in the button group.
This could be some internal change in Qt but maybe it is not safe to translate the index of the button group directly to the intensity mode.
![image](https://user-images.githubusercontent.com/5803621/205855567-426cadc5-12a9-4fac-b8e8-6ce951db67cc.png)

2022-12-06 08:22 UTC, timosachsenberg commented
![image](https://user-images.githubusercontent.com/5803621/205858372-cbbfd70d-64cb-4811-8afd-07a6d07a5b9b.png)

2022-12-09 08:22 UTC, timosachsenberg commented on src/openms/include/OpenMS/KERNEL/AreaIterator.h
> +          ms_level_ = ms_level;
move to initializer list?

2022-12-09 09:11 UTC, cbielow commented on src/openms/include/OpenMS/KERNEL/AreaIterator.h
> +          ms_level_ = ms_level;
yes :)

2022-12-09 09:27 UTC, timosachsenberg approved these changes
only minor / optional things

2022-12-12 15:45 UTC, cbielow commented
now, also the position of annotations is fixed.
This should fix all things related to the large TOPPView pr.
Ready for merge (if tests pass).

2022-12-12 22:03 UTC, jpfeuffer approved these changes

2022-12-13 07:13 UTC, merged