Feature/id ripper speedup2
OpenMS/OpenMS pull request #6590
Opened 2023-01-12 18:23 UTC by timosachsenberg

## Description

significant speed-up from hours to seconds

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2023-01-12 18:25 UTC, timosachsenberg commented
tests pass and results look good to me.
approx. 1000x speedup. now as fast as merging on the data I tested

2023-01-13 09:16 UTC, poshul commented on src/openms/source/ANALYSIS/ID/IDRipper.cpp
> +              //std::cout << "ripped/merged identifier: " << ripped_prot_identifier << " " << prot << std::endl;
Delete

2023-01-13 09:29 UTC, poshul approved these changes

2023-01-14 08:43 UTC, merged

2023-01-14 12:09 UTC, jpfeuffer requested changes
Please add another fix

2023-01-14 12:50 UTC, jpfeuffer commented on src/openms/source/ANALYSIS/ID/IDRipper.cpp
> +        ProteinIdentification p{merged_protein_id_run};
@timosachsenberg

2023-01-14 17:17 UTC, timosachsenberg commented on src/openms/source/ANALYSIS/ID/IDRipper.cpp
> +        ProteinIdentification p{merged_protein_id_run};
Thanks. Yeah I noticed these lines are inefficient and forgot to change it. I can look at it - sounds like ab easy fix.

2023-01-16 11:13 UTC, jpfeuffer commented on src/openms/source/ANALYSIS/ID/IDRipper.cpp
> +        ProteinIdentification p{merged_protein_id_run};
Yes if every protein comes from a different file.
Just write a custom function in the proteinID copyMetadataOnly. It doesn't have so many members.