add MSGF+ allowDenseCentroidedPeaks parameter
OpenMS/OpenMS pull request #6606
Opened 2023-01-18 13:27 UTC by bernt-matthias

## Description

- [ ] add MSGF+ `-allowDenseCentroidedPeaks` parameter
- [ ] add test 
- [ ] always output MSGF+ commandline, stdout and stderr in case of error?

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2023-01-18 14:50 UTC, timosachsenberg commented on src/topp/MSGFPlusAdapter.cpp
> +    if (getFlag_(allow_dense_centroided_peaks)){
```suggestion
    if (getFlag_("allow_dense_centroided_peaks"))
    {
```

2023-01-18 14:51 UTC, bernt-matthias commented on src/topp/MSGFPlusAdapter.cpp
> +    if (getFlag_(allow_dense_centroided_peaks)){
uups :)

2023-01-19 16:15 UTC, jpfeuffer requested changes

2023-01-19 16:30 UTC, bernt-matthias commented on src/tests/topp/THIRDPARTY/third_party_tests.cmake
> +  set_tests_properties("TOPP_MSGFPlusAdapter_1_out2" PROPERTIES DEPENDS "TOPP_MSGFPlusAdapter_1")
Did not meant to commit this yet. Wanted to fix the original test first.

2023-01-19 20:15 UTC, jpfeuffer commented
You have to decide if you want the param with underscores or camelCase. But it needs to be consistent!

2023-01-19 20:25 UTC, jpfeuffer commented
I think you made the right choice with underscores but it needs to be with underscores in the test as well.

2023-01-20 17:19 UTC, bernt-matthias commented
@jpfeuffer user provided me a ~3MB test file that could not be parsed before. Would this be fine? 

Is there a way to get the binaries that are generated by the CI for this PR? Could you remind me where I find the compilation instructions if not.

2023-01-20 17:27 UTC, jpfeuffer commented
If possible, try to run a FileFilter and remove any MS1 spectra and filter for a few MS2 spectra that would fail without the flag. It is on the high end.

Just develop on gitpod.io#https://github.com/OpenMS/OpenMS/pull/6606 . It will be (mostly) precompiled.
Change back the files to separate files (i.e. just copy MSGFPlus_1_out)! Otherwise, you will overwrite. Run `ctest -R MSGFPlusAdapter_2` to check. And `./tools/overwriteTOPPtests.sh MSGFPlusAdapter_2` to overwrite the "groundtruth test files" with the output from the current test run.

2026-06-08 14:53 UTC, timosachsenberg commented
Superseded by #9461, which rebases this onto current `develop`, ports it to the refactored `std::vector<String>` argument handling, and fixes the flag passing (`-allowDenseCentroidedPeaks` and `1` are now separate argv tokens) plus the test reference. Thanks @bernt-matthias — you're credited as co-author on the new commit. Closing in favor of #9461.

2026-06-08 14:53 UTC, closed without merging