Update package_general.cmake
OpenMS/OpenMS pull request #7331
Opened 2024-02-05 10:03 UTC by timosachsenberg

## Description

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2024-02-05 10:03 UTC, timosachsenberg commented
/describe

2024-02-05 10:13 UTC, timosachsenberg commented on cmake/package_general.cmake
> +  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "UxTheme" "d3d11" "WINNMM")
```suggestion
  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "UxTheme" "d3d11" "WINNMM" "wldp")
```

2024-02-05 10:16 UTC, jpfeuffer commented
please use lowercase.
https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies:~:text=DLL%20dependency%20names%20are%20converted%20to%20lowercase%20for%20matching%20filters.

also maybe a folder-based exclude might make sense. Not sure where they all are located. Probably better if someone tests it.

2024-02-05 10:21 UTC, timosachsenberg commented
@JeeH-K can you give this a try after it is merged? (create installer and try to execute)

2024-02-05 10:22 UTC, timosachsenberg commented
I think all of them are in the bin folder. Let's test.

2024-02-05 10:22 UTC, merged

2024-02-05 10:30 UTC, jpfeuffer commented
Yes, but after install ;) this excludes based on the location before installing. But yes, just test it.

2024-02-07 15:10 UTC, JeeH-K commented
@timosachsenberg did it work with your branch?
I tried to merge the corresponding develop branch to mine (https://github.com/OpenMS/OpenMS/commits/FDdevelop/) and tried GHA, still failed.
Installation was successful, yet gave an error message while trying to open ToppView
![Screenshot 2024-02-07 at 4 05 40 PM](https://github.com/OpenMS/OpenMS/assets/7207883/a926c827-19ab-4fa5-a943-227d747ac0ce)

2024-02-07 15:19 UTC, timosachsenberg commented
It never failed on my machine, I think. @JeeH-K I guess you don't have a windows development environment set up (me neither). @cbielow if you have one set up can you check in which folder these dlls are before installation? See Julianus' comment

2024-02-07 15:21 UTC, timosachsenberg commented
Will double check with your installer...

2024-02-07 16:01 UTC, jpfeuffer requested changes

2024-02-07 16:01 UTC, jpfeuffer commented on cmake/package_general.cmake
> +  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "uxtheme" "d3d11" "winnmm" "wldp")
```suggestion
  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "uxtheme" "d3d11" "winmm" "wldp")
```

2024-02-07 16:03 UTC, cbielow commented on cmake/package_general.cmake
> +  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "uxtheme" "d3d11" "winnmm" "wldp")
that should do it.

2024-02-07 16:05 UTC, timosachsenberg commented on cmake/package_general.cmake
> +  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "uxtheme" "d3d11" "winnmm" "wldp")
can add

2024-02-07 16:05 UTC, cbielow commented
> It never failed on my machine, I think. @JeeH-K I guess you don't have a windows development environment set up (me neither). @cbielow if you have one set up can you check in which folder these dlls are before installation? See Julianus' comment

just for completeness, on my machine `winmm.dll` is in C:\Windows\System32
But your system should have it too. Its a very generic dll (Windows Multimedia API)

2024-02-07 16:13 UTC, timosachsenberg commented on cmake/package_general.cmake
> +  set(EXCLUDE "api-ms" "ext-ms" "hvsi" "pdmutilities" "wpaxholder" "dxgi" "uxtheme" "d3d11" "winnmm" "wldp")
Pushed. @JeeH-K

2024-02-07 21:15 UTC, JeeH-K commented
Mine is Windows 10. It worked like a charm after the change from @jpfeuffer! Thanks everyone 👏