add html in selectversion.js
OpenMS/OpenMS pull request #7534
Opened 2024-07-03 06:36 UTC by JKVISION1101

https://github.com/OpenMS/OpenMS-docs/issues/231

## Description

https://github.com/OpenMS/OpenMS-docs/issues/231

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

2024-07-03 07:30 UTC, jpfeuffer requested changes

2024-07-03 07:30 UTC, jpfeuffer commented on doc/doxygen/common/selectversion.js
> +        + '/release/' + x + '/' + 'html/' + patharr[patharr.length - 1] + '">'
```suggestion
        + '/release/' + x + '/html/' + patharr[patharr.length - 1] + '">'
```

2024-07-03 07:30 UTC, jpfeuffer commented on doc/doxygen/common/selectversion.js
> +        + '/release/' + x + '/' + 'html/' + patharr[patharr.length - 1] + '">'
And you forgot the same change for the nightly link, a few lines below.

2024-07-05 00:34 UTC, JKVISION1101 commented
@jpfeuffer 
Thanks for review.

I add 'html/' in the nightly version.

2024-07-09 09:18 UTC, timosachsenberg commented
@jpfeuffer does this look fine to you? merge?

2024-07-09 10:17 UTC, jpfeuffer approved these changes

2024-07-09 11:34 UTC, merged

2024-07-12 00:59 UTC, JKVISION1101 commented
@jpfeuffer 

Thanks for accepting pull request.

Now this code is not applied to openms documentations.

When it will be applied to documentation?

2024-07-12 09:28 UTC, jpfeuffer commented
There you have to ask @timosachsenberg 
I remember the upload having problems